# Everything that's downloaded after cloning Chromium goes here.
# It will not work from main downloads.ini
[search_engines_data]
version = 202607242007
url = https://github.com/imputnet/helium-nonfree-assets/releases/download/%(version)s/nonfree-search-engines-data-%(version)s.tar.gz
download_filename = nonfree-search-engines-data-%(version)s.tar.gz
sha256 = e14fa5b38ced15ae516143da23edcba608eea63e54960173ae8829f08efffb58
output_path = ./third_party/search_engines_data/resources_internal

[onboarding]
version = 202607241958
url = https://github.com/imputnet/helium-onboarding/releases/download/%(version)s/helium-onboarding-%(version)s.tar.gz
download_filename = onboarding-page-%(version)s.tar.gz
sha256 = 3e026530dd93f5ef660f66d21bc7547123b053984a44d6ce310696c9dded98ce
output_path = ./components/helium_onboarding

# If you are bumping this, you *NEED* to re-strip the assets.json
# file *every time* by using `devutils/clear-ublock-assets.js`.
[ublock_origin]
version = 1.72.2
url = https://github.com/imputnet/uBlock/releases/download/%(version)s/uBlock0_%(version)s.chromium.zip
sha256 = 6ea10a863eb343ddcc317fdda9c65ccb2799c74d0de06ad75aded04d38d63dca
download_filename = ublock-origin-%(version)s.zip
output_path = third_party/ublock
strip_leading_dirs = uBlock0.chromium
