# Everything that's downloaded after cloning Chromium goes here.
# It will not work from main downloads.ini
[search_engines_data]
version = 202607242007
url = https://github.com/imputnet/helium-nonfree-assets/releases/download/%(version)s/nonfree-search-engines-data-%(version)s.tar.gz
download_filename = nonfree-search-engines-data-%(version)s.tar.gz
sha256 = e14fa5b38ced15ae516143da23edcba608eea63e54960173ae8829f08efffb58
output_path = ./third_party/search_engines_data/resources_internal

[onboarding]
version = 202607301504
url = https://github.com/imputnet/helium-onboarding/releases/download/%(version)s/helium-onboarding-%(version)s.tar.gz
download_filename = onboarding-page-%(version)s.tar.gz
sha256 = da303b99461c92464f07b6bed67166c2d372abaf9b3a09bb73e3864d0cbe690a
output_path = ./components/helium_onboarding

# If you are bumping this, you *NEED* to re-strip the assets.json
# file *every time* by using `devutils/clear-ublock-assets.js`.
[ublock_origin]
version = 1.73.0
url = https://github.com/imputnet/uBlock/releases/download/%(version)s/uBlock0_%(version)s.chromium.zip
sha256 = 28a2cfc06412cf6b0d2ec8dfbc40c7db731a3324d171497c919433c59c272ae9
download_filename = ublock-origin-%(version)s.zip
output_path = third_party/ublock
strip_leading_dirs = uBlock0.chromium
