# Prepared Chromium source code archive
# NOTE: Substitutions beginning with underscore are provided by utils
[chromium]
url = https://tarballs.imput.net/chromium-%(_chromium_version)s/chromium-%(_chromium_version)s-base.tar.zst
download_filename = chromium-%(_chromium_version)s-base.tar.zst
# TODO: remove -r4 on next version bump, needed because we have immutable releases and i messed up the first release
hash_url = chromium|chromium-%(_chromium_version)s-base.tar.zst.hashes|https://github.com/imputnet/chromium-tarballs/releases/download/chromium-%(_chromium_version)s-r4/chromium-%(_chromium_version)s-base.tar.zst.hashes
output_path = ./
strip_leading_dirs = chromium-%(_chromium_version)s
